Restructuring Repo

diff --git a/Installer b/Installer
--- a/Installer
+++ b/Installer
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+dotfilesPath="~/Github/MyDotFiles"
+
 # Verifica que el usuario no sea root
 if [ "$(whoami)" == "root" ]; then
   exit 1
@@ -15,7 +17,7 @@ packages=(
   lsd  lxappearance  mdcat  neofetch  neovim  onefetch  picom
   playerctl  pokemon-colorscripts-git  polybar  ranger  rofi
   sxhkd  thunar  thunar-volman  wget  xorg-xsetroot  xorg-xinput vlc zsh unzip
-  xrandr sddm
+  xrandr sddm pamixer mpd mpc 
 )
 
 extra_packages=(
@@ -26,15 +28,42 @@ extra_packages=(
   urbanlifestyle-sddm-theme  vim  zip
 )
 
+###
+###
+###
+ask_yn() {
+    while true; do
+        read -p "$1 (y/n): " yn
+        case $yn in
+            [Yy]* ) return 0;;  # Return 0 (success) for yes
+            [Nn]* ) return 1;;  # Return 1 (failure) for no
+            * ) echo "Please answer y or n.";;
+        esac
+    done
+}
+###
+###
+###
+
 # Instalar paru si no está instalado
 install_paru(){
   if ! command -v paru &>/dev/null; then
-      echo "\n>> Instalando paru...\n"
+      echo "\n>> Instalando paru (AUR helper)...\n"
       git clone https://aur.archlinux.org/paru.git
       cd paru
       makepkg -si
       cd ..
       rm -rf paru
+  fi
+}
+
+# Instalar yay si no está instalado
+install_yay(){
+  if ! command -v yay &> /dev/null; then
+    echo "\n>> Instalando yay (AUR helper)...\n"
+    sudo pacman -Syu --needed base-devel git
+    git clone https://aur.archlinux.org/yay.git ~/yay
+    (cd ~/yay && makepkg -si)
   fi
 }
 
@@ -62,16 +91,17 @@ install_blackarch_repo(){
 }
 
 copy_files(){
+  local dotfilesPathBspwm="$dotfilesPath/BSPWM"
   echo "\n>> Copiando archivos de configuración...\n"
 
-  cp -r ~/Github/MyDotFiles/.config/bspwm ~/.config/
-  cp -r ~/Github/MyDotFiles/.config/neofetch ~/.config/
-  cp -r ~/Github/MyDotFiles/.config/rofi ~/.config/
-  cp -r ~/Github/MyDotFiles/.config/kitty/ ~/.config/
-  cp -r ~/Github/MyDotFiles/.config/jgmenu/ ~/.config/
-  cp -r ~/Github/MyDotFiles/.config/ranger/ ~/.config/
-  cp ~/Github/MyDotFiles/.config/wallpaper.conf ~/.config/
-  cp ~/Github/MyDotFiles/.config/.zshrc ~/
+  cp -r $dotfilesPathBspwm/.config/bspwm ~/.config/
+  cp -r $dotfilesPathBspwm/.config/neofetch ~/.config/
+  cp -r $dotfilesPathBspwm/.config/rofi ~/.config/
+  cp -r $dotfilesPathBspwm/.config/kitty/ ~/.config/
+  cp -r $dotfilesPathBspwm/.config/jgmenu/ ~/.config/
+  cp -r $dotfilesPathBspwm/.config/ranger/ ~/.config/
+  cp $dotfilesPathBspwm/.config/wallpaper.conf ~/.config/
+  cp $dotfilesPathBspwm/.config/.zshrc ~/
   
   [ ! -d ~/.local/share/fonts ] && mkdir -p ~/.local/share/fonts
   [ ! -d ~/.local/share/icons ] && mkdir -p ~/.local/share/icons
@@ -79,14 +109,33 @@ copy_files(){
   [ ! -d ~/.local/share/rofi ] && mkdir -p ~/.local/share/rofi
 
   mkdir ~/.local/share/fonts/Hack
-  unzip ~/Github/MyDotFiles/.local/share/fonts/HackNerdFont.zip -d ~/.local/share/fonts/Hack
-  tar xfv ~/Github/MyDotFiles/.local/share/icons/Simp1e-Tokyo-Night-Storm.tgz
-  mv ~/Github/MyDotFiles/.local/share/icons/Simp1e-Tokyo-Night-Storm ~/.local/share/icons
-  unzip ~/Github/MyDotFiles/.local/share/icons/Tokyonight-Dark-Icons.zip -d ~/.local/share/icons
-  unzip ~/Github/MyDotFiles/.local/share/themes/Tokyonight-Storm-B.zip -d ~/.local/share/themes
-  cp -r ~/Github/MyDotFiles/.local/share/rofi -d ~/.local/share/
+  unzip $dotfilesPathBspwm/.local/share/fonts/HackNerdFont.zip -d ~/.local/share/fonts/Hack
+  tar xfv $dotfilesPathBspwm/.local/share/icons/Simp1e-Tokyo-Night-Storm.tgz
+  mv $dotfilesPathBspwm/.local/share/icons/Simp1e-Tokyo-Night-Storm ~/.local/share/icons
+  unzip $dotfilesPathBspwm/.local/share/icons/Tokyonight-Dark-Icons.zip -d ~/.local/share/icons
+  unzip $dotfilesPathBspwm/.local/share/themes/Tokyonight-Storm-B.zip -d ~/.local/share/themes
+  cp -r $dotfilesPathBspwm/.local/share/rofi -d ~/.local/share/
 }
 
+# Directorio de respaldo para la configuración existente
+BACKUP_DIR="$HOME/backup_$(date +%Y%m%d_%H%M%S)"
+mkdir -p "$BACKUP_DIR"
+
+backup_files_and_copy_dots() {
+    local src=$1
+    local dest=$2
+    if [ -e "$dest" ]; then
+        echo "Backing up existing $(basename "$dest") to $BACKUP_DIR"
+        mv "$dest" "$BACKUP_DIR"
+    fi
+    cp -rf "$src" "$dest"
+}
+
+
+# <---------------------------------------Funciones de Instalación--------------------------------------->
+
+
+# Bare Install (START) #
 config(){
   git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
 }
@@ -105,8 +154,10 @@ bare_install(){
   config config status.showUntrackedFiles no
 }
 
-# Instalar
-install(){
+# Bare Install (END) #
+
+# Instalar bspwm
+install_bspwm(){
   # Creando carpeta de Dotfiles
   echo "\n>> Clonando Repositorio\n"
   cd
@@ -141,7 +192,7 @@ install(){
   rofi-theme-selector
 
   # Removiendo Repositorio
-  ecoh "\n>> Limpiando archivos...\n"
+  echo "\n>> Limpiando archivos...\n"
   rm -rf ~/Github
 
   # Mensaje de Instalado
@@ -149,19 +200,93 @@ install(){
   notify-send "BSPWM INSTALADO"
 }
 
+# Instalar hyprland
+install_hyprland(){
+  local dotfilesPathHypr="$dotfilesPath/HYPRLAND" 
+  # Creando carpeta de Dotfiles
+  echo "\n>> Clonando Repositorio\n"
+  cd
+  mkdir Github
+  cd Github/
+  git clone --depth=1 https://github.com/Panther-14/MyDotFiles.git
+
+  # Instalar paru como AUR helper
+  install_paru
+
+  # Instalar o actualizar paquetes
+  install_packages
+
+  # Cambia el shell del usuario actual a zsh
+  echo "\n>> Cambiando shell...\n" 
+  chsh -s "$(which zsh)"
+
+  # Instalar Oh My Zsh para el usuario actual
+  echo "\n>> Instalando Oh My Zsh...\n"
+  sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
+
+  # Instalar plugins zsh
+  echo "\n>> Instalando plugins omz...\n"
+  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
+  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
+
+
+  # Copiamos configuración
+  backup_files_and_copy_dots "$dotfilesPathHypr/.config/" "$HOME/.config/"
+
+  backup_files_and_copy_dots "$dotfilesPathHypr/.zshrc" "$HOME/.zshrc"
+
+  [ ! -d ~/.local/share/fonts ] && mkdir -p ~/.local/share/fonts
+  [ ! -d ~/.local/share/icons ] && mkdir -p ~/.local/share/icons
+  [ ! -d ~/.local/share/themes ] && mkdir -p ~/.local/share/themes
+  [ ! -d ~/.local/share/rofi ] && mkdir -p ~/.local/share/rofi
+
+  mkdir ~/.local/share/fonts/Hack
+  unzip $dotfilesPathHypr/.local/share/fonts/HackNerdFont.zip -d ~/.local/share/fonts/Hack
+  tar xfv $dotfilesPathHypr/.local/share/icons/Simp1e-Tokyo-Night-Storm.tgz
+  mv $dotfilesPathHypr/.local/share/icons/Simp1e-Tokyo-Night-Storm ~/.local/share/icons
+  unzip $dotfilesPathHypr/.local/share/icons/Tokyonight-Dark-Icons.zip -d ~/.local/share/icons
+  unzip $dotfilesPathHypr/.local/share/themes/Tokyonight-Storm-B.zip -d ~/.local/share/themes
+  cp -r $dotfilesPathHypr/.local/share/rofi -d ~/.local/share/
+
+  # Removiendo Repositorio
+  echo "\n>> Limpiando archivos...\n"
+  rm -rf ~/Github
+
+  # Mensaje de Instalado
+  echo "\n>> Proceso de instalación y configuración completado.\n"
+
+}
+
 # <---------------------------------------Instalación--------------------------------------->
 
 case "$1" in
-  --bare)
-    bare_install
+  --bspwm)
+    case "$2" in
+    --black)
+      echo "\n>> Instalación BlackArch seleccionada.\n"
+      install_blackarch_repo
+      install_bspwm
+    ;;
+    --white|*)
+      echo "\n>> Instalación base seleccionada.\n"
+      install_bspwm
+    ;;
+    esac
   ;;
-  --black)
-    echo "\n>> Instalación BlackArch seleccionada.\n"
-    install_blackarch_repo
-    install
+  --hyprland)
+    case "$2" in
+    --black)
+      echo "\n>> Instalación BlackArch seleccionada.\n"
+      install_blackarch_repo
+      install_hyprland
+    ;;
+    --white|*)
+      echo "\n>> Instalación base seleccionada.\n"
+      install_hyprland
+    ;;
+    esac
   ;;
-  --white|*)
-    echo "\n>> Instalación base seleccionada.\n"
-    install
+  *)
+    echo "\n Debes seleccionar un entorno (hyprland/bspwm)\n"
   ;;
 esac
